[package]
name = "bio_diff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
differ-rs = { path = "/Users/alfredo/Documents/differ.rs/crates/differ"}